version: "3.2"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    container_name: mooncake
    environment:
      RAILS_MASTER_KEY: ${MOONCAKE_MASTER_KEY}
      MOONCAKE_OAUTH_KEY: ${MOONCAKE_OAUTH_KEY}
      MOONCAKE_OAUTH_REDIRECT: ${MOONCAKE_OAUTH_REDIRECT}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    volumes:
      - .:/webapp
      - /webapp/node_modules
      - type: tmpfs
        target: /webapp/tmp
