version: "3.2"
services:
  app:
    build: .
    command: /webapp/bin/start_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    container_name: mooncake
    environment:
      RAILS_MASTER_KEY: 6a7d9fb5be62958a8321974b3dfeed1d
    volumes:
      - .:/webapp
      