version: "3.2"
services:
  app:
    build: .
    command: /webapp/bin/start_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    container_name: mooncake
    volumes:
      - .:/webapp
